config/routes.rb
Rails.application.routes.draw do

  root to: 'landing#index'

  resources :users, only: [:new, :create, :show]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :users

  validates :name, presence: true
  
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  belongs_to :category

  validates_confirmation_of :password

  validates :first_name,
            :last_name,
            :street_number,
            :city,
            :state,
            :zip_code,
            :email,
            :picture,
            :phone,
            :category_id, presence: true

  validates :email, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  def index
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def destroy
    session.destroy
    flash[:success] = "You Successfully Logged out!"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    @categories = Category.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      @categories = Category.all
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :street_number,
                                 :unit_number,
                                 :city,
                                 :state,
                                 :zip_code,
                                 :phone,
                                 :email,
                                 :password,
                                 :password_confirmation,
                                 :picture,
                                 :category_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ItTakesAVillage</title>
  <%= csrf_meta_tags %>

</head>
  <% if current_user.nil?  %>
    <%= link_to "Log In", login_path %> | <%= link_to "Sign Up", new_user_path %>
  <% else %>
    <%= link_to "Log Out", logout_path %>
  <% end %>

<body>
  <%= yield %>
</body>


</html>

app/views/users/new.html.erb
Create Your New Account and Help a Friend

<%= form_for @user do |f| %>
<%= f.label "First Name" %>
<%= f.text_field :first_name, placeholder: "**REQUIRED**" %>

<%= f.label "Last Name" %>
<%= f.text_field :last_name, placeholder: "**REQUIRED**" %>

<%= f.label "Street Address" %>
<%= f.text_field :street_number, placeholder: "**REQUIRED**" %>

<%= f.label "Unit Number" %>
<%= f.text_field :unit_number, placeholder: "If Applicable" %>

<%= f.label "City" %>
<%= f.text_field :city, placeholder: "**REQUIRED**" %>

<%= f.label "State" %>
<%= f.text_field :state, placeholder: "**REQUIRED**" %>

<%= f.label "Zip" %>
<%= f.text_field :zip_code, placeholder: "**REQUIRED**" %>

<%= f.label "Phone Number" %>
<%= f.text_field :phone, placeholder: "**REQUIRED**" %>

<%= f.label "Email" %>
<%= f.text_field :email, placeholder: "**REQUIRED**" %>

<%= f.label "Password" %>
<%= f.password_field :password, placeholder: "**REQUIRED**" %>

<%= f.label "Password" %>
<%= f.password_field :password_confirmation, placeholder: "**REQUIRED**" %>

<%= f.label "A Picture of You" %>
<%= f.text_field :picture, placeholder: "**REQUIRED**" %>

<%= f.collection_select :category_id, @categories,:id,:name, include_blank: true %>

<%= f.submit "Create Account!" %>
<% end %>

app/views/users/show.html.erb
Hey <%= @user.first_name %>